# Ruffの設定（リンターとフォーマッター）

# ターゲットとするPythonバージョン
target-version = "py39"
# 行の長さ制限
line-length = 100
# インデントの幅
indent-width = 4
# 対象とするファイル
include = ["*.py", "*.pyi"]
# 除外するファイル
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    "venv",
    "__pycache__",
    "build",
    "dist",
]

# リンターの設定
[lint]
# 有効にするルール
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "W",   # pycodestyle warnings
    "C90", # mccabe
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "SIM", # flake8-simplify
    "RUF", # Ruff-specific rules
]
# 無視するルール
ignore = [
    "E203",  # whitespace before ':'
    "E501",  # line too long
]
# 未使用のインポートを自動的に削除
unfixable = ["F401"]

# isortの設定
[lint.isort]
known-first-party = ["agent_utils"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

# フォーマッターの設定
[format]
# クォートスタイル: ダブルクォート
quote-style = "double"
# インデントスタイル: スペース
indent-style = "space"
# 行末のカンマ: 可能な場合は追加
line-ending = "auto"
# docstringのクォートスタイル: ダブルクォート
docstring-code-format = true
# Blackと互換性のあるフォーマット
skip-magic-trailing-comma = false
